### ISSUE TITLE
Using Lenovo l340 efi

### ISSUE THREAD

**Issue by rosostolato** [dragons3232/Lenovo-gaming-3-10750h-hackintosh-EFI#3]
Hey there, I've being using the Lenovo l340 efi. Here is the link (I'm using the opencore version): https://github.com/khanhtran-cse/lenovo-ideapad-l340-hackintosh

There's no problem with the speakers. Also, there was no issue with brightness, neither when installing nor after... That's good... but I can't get the TouchPad to work neither.  

To fix the TouchPad, I've tried to download the latest voodooi2c kexts for hid, but I had no success. Does anyone have any clue of what we could do to make it work?

It seems that this efi is better than the version of this repository, so maybe we can update it and investigate to find a way to fix the TouchPad.

**Comment by dragons3232** [comment]
I tried many articles but I couldn't fix Touchpad issue. The easiest solution for me was to use external usb mouse. I rarely use touchpad to be honest. I wish I had leisure days so that I can fix hdmi issue. It is more used to me. I tried couple of times but no luck. Not sure why hackintosh is so hard to switch graphics and feed to hdmi output. Hope someone figure out a solution

**Comment by rosostolato** [comment]
I don't know for sure, but I believe that this laptop uses I2C-HID touchpad, but I don't know which model it is. But it seems that it should work with the latest release from the [github project,](https://github.com/VoodooI2C/VoodooI2C), I can't say why it doesn't. It would be helpful to me because I use some pinch funcionalities.

And about hdmi, I read that the hdmi port is connected directly via the gtx 1650 video card and since macOS doesn't support nvidia anymore, it's necessary to disable the card which disables the port too. I was going to try those usb-c hub that converts usb to HDMI, but I think you have already tried that, right? On the l340 github page, they said that usb to HDMI adapter works, but, fot me, it would be better to use the usb-c port 'cause it doesn't have many common usb ports.

If we could fix these 2 problems, it would be enough. I bought this laptop thinking that it would be easier to use hackintosh due the fact it's an intel processor, but it has been tougher than installing ryzentosh on my pc with ryzen and amd video card.

**Comment by dragons3232** [comment]
I already tried 3 usb c to hdmi adapters but they did not work. That's weird isn't it ? That made me think hackintosh hdmi support is bad :(

**Comment by rosostolato** [comment]
> I already tried 3 usb c to hdmi adapters but they did not work. That's weird isn't it ? That made me think hackintosh hdmi support is bad :(

Have you tried with common usb to hdmi adapters? In theory, if a common usb adapter works, it should also work for usb-c because it's just usb 3.1 in a usb-c port... so it should be the same. If it only had support for usb-c display port...

**Comment by dragons3232** [comment]
Hi @rosostolato ,
I tried Unitek y-3702 USB 3.0 to HDMI and it worked perfectly on my hackintosh Big Sur (I upgraded a week ago).
I could not find driver for it at first. But then I realized that I had to switch slide. All drivers for their products could be found at: https://www.unitek-products.com/pages/driver-manuals
OR you can also download driver for above model from Google drive at:
https://drive.google.com/drive/folders/1mKwJA7hpeSwwQAW9P4u7nzkQAI8WowwT

**Comment by rosostolato** [comment]
> Hi @rosostolato ,
> I tried Unitek y-3702 USB 3.0 to HDMI and it worked perfectly on my hackintosh Big Sur (I upgraded a week ago).
> I could not find driver for it at first. But then I realized that I had to switch slide. All drivers for their products could be found at: https://www.unitek-products.com/pages/driver-manuals
> OR you can also download driver for above model from Google drive at:
> https://drive.google.com/drive/folders/1mKwJA7hpeSwwQAW9P4u7nzkQAI8WowwT

Does it support 4k?

**Comment by dragons3232** [comment]
I cannot verify it yet. I only have a full hd monitor. On Unitek product page, it is stated that the adapter supports Full HD 1080P. But some retailer mentioned on their page that it can support 2k.

**Comment by farhannovan** [comment]
> Hey there, I've being using the Lenovo l340 efi. Here is the link (I'm using the opencore version): https://github.com/khanhtran-cse/lenovo-ideapad-l340-hackintosh
> 
> There's no problem with the speakers. Also, there was no issue with brightness, neither when installing nor after... That's good... but I can't get the TouchPad to work neither.
> 
> To fix the TouchPad, I've tried to download the latest voodooi2c kexts for hid, but I had no success. Does anyone have any clue of what we could do to make it work?
> 
> It seems that this efi is better than the version of this repository, so maybe we can update it and investigate to find a way to fix the TouchPad.


Hi, it's work for Big Sur?

**Comment by farhannovan** [comment]
> I cannot verify it yet. I only have a full hd monitor. On Unitek product page, it is stated that the adapter supports Full HD 1080P. But some retailer mentioned on their page that it can support 2k.

Hi. I want to say thank you very much for efi big sur v3, it works according to what you wrote. I'm waiting for the next efi update so that the audio can work. Thank you :)

**Comment by dragons3232** [comment]
You are welcome @farhannovan. I also want to have audio work. Just that left and it is enough for me to enjoy Big Sur on this lenovo gaming3. I tried to fix it before but it did not work unfortunately. I will try again some day and update EFI version when I can fix it. Hope I can do that soon

**Comment by farhannovan** [comment]
Okay @dragons3232 , I'm waiting for the next good news. 
Btw your messages and facetime can login and run normally? because on my laptop I can't login even though I have generated SMBIOS but for the app store, tv, etc it works. Thank you in advance

**Comment by farhannovan** [comment]
> You are welcome @farhannovan. I also want to have audio work. Just that left and it is enough for me to enjoy Big Sur on this lenovo gaming3. I tried to fix it before but it did not work unfortunately. I will try again some day and update EFI version when I can fix it. Hope I can do that soon

Okay, I'm waiting for the next good news. 
Btw your messages and facetime can login and run normally? because on my laptop I can't login even though I have generated SMBIOS but for the app store, tv, etc it works. Thank you in advance

**Comment by farhannovan** [comment]
@dragons3232 one more, what version of opencore are you using for big sur? thank you

**Comment by farhannovan** [comment]
Hi, I just found a repo whose audio works, here's the link https://github.com/maycon2-0/Hackintoh-Ideapad-Gaming-3i

**Comment by dragons3232** [comment]
That is great to know. Thank you very much for sharing @farhannovan. I will check it out when possible and update EFI

**Comment by farhannovan** [comment]
FYI: 
![image](https://user-images.githubusercontent.com/71864414/143407819-ded22308-f87b-40dc-97dd-0a32bd5d0447.png)

and I have a issue, if I sleep and want to wake up the screen is blank.

**Comment by dragons3232** [comment]
Hi @farhannovan , I have just uploaded a new EFI that contains fix for audio speaker and microphone. Thanks for pointing out above repo that helped me a lot to resolve the issue with audio. Now almost all the hardwares work for me. Enjoy !

**Comment by farhannovan** [comment]
Thank you so much, I will try it later. 
Btw, what version of opencore do you use?

**Comment by dragons3232** [comment]
Hi @farhannovan , you can do it like that in terminal, execute this command
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version
=> result: 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version	REL-065-2021-01-04

**Comment by farhannovan** [comment]
Oh thank you.
One more question, what method do you use to write and read for ntfs?

**Comment by dragons3232** [comment]
Hi @farhannovan,
AFAIK, NTFS is proprietary to MS and Mac cannot write to NTFS by default. You need a third party app like this one https://osxfuse.github.io/

**Comment by farhannovan** [comment]
> Hi @farhannovan, AFAIK, NTFS is proprietary to MS and Mac cannot write to NTFS by default. You need a third party app like this one https://osxfuse.github.io/

Thank you.
Btw, I have an issue about sleep and when I wake up it goes blank, is it the same with you @dragons3232 ? Thanks in advance

**Comment by dragons3232** [comment]
Hi @farhannovan, I encounter the same issue. I tried various versions of Lilu but it did not work. Perhaps we need new SSDT-PNLF-CFL.aml . I will try to find a fix for it as soon as possible

**Comment by dragons3232** [comment]
Hi @farhannovan , I have fixed issue with black screen on waking up from sleep. Please check out the latest EFI version. Enjoy!

**Comment by farhannovan** [comment]
> Hi @farhannovan , I have fixed issue with black screen on waking up from sleep. Please check out the latest EFI version. Enjoy!

Thank you so much bro, it's working.
I have a question, can this be overridden or start from 0? because I reinstalled from scratch.

**Comment by dragons3232** [comment]
Hi @farhannovan,
I am sorry I don't understand. If you meant to start building OC EFI from scratch, please refer to OC documents. I did not follow all the steps and sections. I reused OC EFI (which could boot) from a forum that I no longer remember its name. At start, it had a lot of issues, then I copied some fixes from other OC EFI fixes. I tested a lot. And I followed OC docs to fix some issues with black screen, usb ports, camera. It is a mix of many fixes actually :))
Anyway, I think you can start over by downloading OC EFI, and copying fixes from EFI on this repo to your need. AFAIK, it is often about missing kexts, missing hardware map or layout, or aml files

**Comment by dragons3232** [comment]
Reported issues in this thread have been resolved, it is now closed. Feel fee to open another issue if any

**Comment by farhannovan** [comment]
Thank you!

**Comment by farhannovan** [comment]
hi @dragons3232  I want to ask, how do you fix black screen on waking up from sleep? Because I use my own efi but have problems with sleep and wake. Thanks in advance
